@echo off
setlocal
cd /d "%~dp0"

set "NODE_CMD="
for /f "delims=" %%I in ('where node 2^>nul') do if not defined NODE_CMD set "NODE_CMD=%%I"
if not defined NODE_CMD if exist .cache\node22\node-path.txt set /p NODE_CMD=<.cache\node22\node-path.txt

if not defined NODE_CMD (
  echo [ERROR] Node.js runtime was not found.
  pause
  exit /b 1
)

echo ==========================================================
echo   Buju / Taipei-Maps - Overture Places audit spike v0.12
echo   Issue #56 - strict-chain non-overlapping pair audit
echo ==========================================================
echo.
echo This spike intentionally simplifies the duplicate audit:
echo   - strict known-chain recognition; no bare substring match for FamilyMart
echo   - canonical POI rendering is generated by the same JS normalization used by audit
echo   - review queue samples A/B pairs only; no transitive candidate families
echo   - the same raw record appears at most once in one Top-15 review round
echo   - candidate and canonical POI points are clickable
echo   - popup includes raw name, raw brand, branch, source, address and Overture id
echo   - obvious outside-Taipei place-name conflicts are flagged as source-quality anomalies
echo   - a dedicated misplaced/anomalous verdict is available
echo   - all judgments remain audit-only; no automatic merge/delete
echo.
echo Visual audit checklist:
echo   1. Wait for READY.
echo   2. Click ^"產生最可疑 Top 15^".
echo   3. Each review item should contain only A and B, both the same canonical chain.
echo   4. The unrelated water-equipment record previously matched by the word ^"全家^" should disappear from FamilyMart candidates.
echo   5. A PX Mart record whose text says 桃園 while plotted in Taipei should show a geo-name anomaly warning.
echo   6. Click A/B and normal blue/orange points to inspect raw/source/address details.
echo   7. Mark each pair same store / different store / misplaced-anomalous / unsure.
echo.
echo Keep this window open. Press Ctrl+C to stop the local server.
echo.
"%NODE_CMD%" tools\dev\serve_single_engine_core.mjs 5173 "/daily-life-poi-overture-spike-v12.html"
exit /b %errorlevel%
