#!/usr/bin/env python3
"""Generate browser-ready Taipei 115 school-district bootstrap + district shards."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import build_taipei_school_districts as builder

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BOOTSTRAP = ROOT / "public" / "taipei-school-districts-115.js"
DEFAULT_SHARD_DIR = ROOT / "public" / "school-districts-115"

VILLAGE_NAME_FIXES = {
    ("信義", "三犛"): "三犁",
    ("中山", "恒安"): "恆安",
    ("萬華", "柳郷"): "柳鄉",
    ("萬華", "糖蔀"): "糖廍",
    ("內湖", "葫州"): "葫洲",
}


def normalize_extracted(level: str, table: dict[str, dict]) -> dict[str, dict]:
    out = {}
    for key, entry in table.items():
        district, village = key.split("|", 1)
        village = VILLAGE_NAME_FIXES.get((district, village), village)
        fixed_key = f"{district}|{village}"
        if fixed_key in out:
            raise RuntimeError(f"{level}: normalization collision at {fixed_key}")
        entry = json.loads(json.dumps(entry, ensure_ascii=False))
        targets = [entry] if "all" in entry else entry.get("rules", [])
        for target in targets:
            field = "all" if "all" in target else "school"
            school = target[field]
            school = school.replace("、共同學區", "共同學區")
            if level == "elementary":
                school = school.replace("國小共同學區", "共同學區")
            target[field] = school
        out[fixed_key] = entry
    return out


def assert_same_villages(elementary: dict[str, dict], junior: dict[str, dict]) -> None:
    for district in builder.DISTRICTS:
        e = {k.split("|", 1)[1] for k in elementary if k.startswith(f"{district}|")}
        j = {k.split("|", 1)[1] for k in junior if k.startswith(f"{district}|")}
        if e != j:
            raise RuntimeError(f"{district}: elementary/junior village-name mismatch: E-only={sorted(e-j)}, J-only={sorted(j-e)}")


def js_json(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def write_outputs(dataset: dict, bootstrap_path: Path, shard_dir: Path) -> None:
    bootstrap = {**dataset, "levels": {"elementary": {}, "junior": {}}}
    bootstrap_path.parent.mkdir(parents=True, exist_ok=True)
    bootstrap_path.write_text(
        "// Generated bootstrap. District assignments live in public/school-districts-115/*.js.\n"
        "(()=>{\n"
        f"const dataset={js_json(bootstrap)};\n"
        "window.TaipeiMapsSchoolDistrictData115=dataset;\n"
        "})();\n",
        encoding="utf-8",
    )

    shard_dir.mkdir(parents=True, exist_ok=True)
    for district in builder.DISTRICTS:
        elementary = {k: v for k, v in dataset["levels"]["elementary"].items() if k.startswith(f"{district}|")}
        junior = {k: v for k, v in dataset["levels"]["junior"].items() if k.startswith(f"{district}|")}
        text = (
            "// Generated by tools/data/generate_taipei_school_district_shards.py. Do not hand-edit.\n"
            "(()=>{const d=window.TaipeiMapsSchoolDistrictData115;"
            "if(!d)throw new Error('Taipei school-district bootstrap missing');"
            f"Object.assign(d.levels.elementary,{js_json(elementary)});"
            f"Object.assign(d.levels.junior,{js_json(junior)});"
            "})();\n"
        )
        (shard_dir / f"{district}.js").write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bootstrap-out", type=Path, default=DEFAULT_BOOTSTRAP)
    parser.add_argument("--shard-dir", type=Path, default=DEFAULT_SHARD_DIR)
    parser.add_argument("--cache-dir", type=Path, default=builder.DEFAULT_CACHE)
    parser.add_argument("--offline", action="store_true")
    parser.add_argument("--elementary-pdf", type=Path)
    parser.add_argument("--junior-pdf", type=Path)
    args = parser.parse_args()

    paths = {}
    for level, supplied in [("elementary", args.elementary_pdf), ("junior", args.junior_pdf)]:
        path = supplied or builder.download_source(level, args.cache_dir, args.offline)
        actual = builder.sha256(path)
        expected = builder.SOURCES[level]["sha256"]
        if actual != expected:
            raise RuntimeError(f"{level}: checksum mismatch for {path}: {actual} != {expected}")
        paths[level] = path

    elementary = normalize_extracted("elementary", builder.extract_pdf(paths["elementary"], "elementary"))
    junior = normalize_extracted("junior", builder.extract_pdf(paths["junior"], "junior"))
    assert_same_villages(elementary, junior)
    dataset = builder.build_dataset(elementary, junior)
    write_outputs(dataset, args.bootstrap_out, args.shard_dir)
    print(json.dumps(dataset["generated"]["validation"], ensure_ascii=False, indent=2))
    print(f"Wrote bootstrap: {args.bootstrap_out}")
    print(f"Wrote {len(builder.DISTRICTS)} district shards: {args.shard_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
